### ISSUE TITLE
Use nseg in regular javascript

### ISSUE THREAD

**Issue by lwbdev** [mountain/nseg#1]
Hi, do you know how much work it would take to get this to work in normal javascript? I would like to use this in a phonegap app if possible.

**Comment by mountain** [comment]
I think it is possile, please take a look the code:
- from https://github.com/mountain/nseg/blob/master/lib/evented.js#L70
- to https://github.com/mountain/nseg/blob/master/lib/evented.js#L76

These are the core part of nseg.

At least, below files are needed:
- mmseg algorithm: https://github.com/mountain/nseg/blob/master/lib/filter.js
- lexer: https://github.com/mountain/nseg/blob/master/lib/lexer.js
- matcher: https://github.com/mountain/nseg/blob/master/lib/matcher.js

**Comment by lwbdev** [comment]
Thanks for the tips. I'll give a shot and see how it goes.
